[build]
builder = "NIXPACKS"

[deploy]
startCommand = "pnpm --filter @orenna/api run start:migrate"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
buildCommand = "pnpm run build"
startCommand = "pnpm --filter @orenna/api run start:migrate"