[build]
builder = "NIXPACKS"

[deploy]
startCommand = "pnpm --filter @orenna/api run prisma:deploy && pnpm --filter @orenna/api start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
buildCommand = "pnpm run build"
startCommand = "pnpm --filter @orenna/api run prisma:deploy && pnpm --filter @orenna/api start"