[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"

# Solc compiler settings - Updated EVM version
solc = "0.8.24"
evm_version = "cancun"  # Changed from "paris" to support mcopy
optimizer = true
optimizer_runs = 200
via_ir = false

# Formatter settings
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"

# Testing settings
fuzz = { runs = 256 }
invariant = { runs = 256, depth = 15 }

# Gas reporting
gas_reports = ["*"]

# RPC endpoints for deployment and testing
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
localhost = "http://127.0.0.1:8545"

# Etherscan API keys for verification
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }

# Libraries and remappings
[dependencies]
openzeppelin-contracts = "5.0.1"

# Profile-specific overrides
[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000, depth = 20 }

[profile.lite]
optimizer = false
fuzz = { runs = 32 }
invariant = { runs = 32, depth = 10 }
